## Manual Search

### KNN

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [3]:
df= sns.load_dataset("iris")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df['species'].value_counts()
#df['species'].unique()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x= df.drop('species',axis=1)
y= df['species']

In [8]:
x_train, x_test,y_train,y_test= train_test_split(x,y,test_size=0.33, random_state=42)

In [10]:
from sklearn.neighbors import  KNeighborsClassifier

In [11]:
model_knn= KNeighborsClassifier(n_neighbors=3)  # 13 for max acc
# manually change the n to find max accuracy. ex- 3,5,7,9,11,13

In [12]:
model_knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [13]:
model_knn.score(x_test,y_test)

0.98

### SVM

In [15]:
from sklearn.svm import SVC

In [16]:
model_svm= SVC(gamma='auto')  # change the value of kernel and c value to find max accuracy

In [17]:
model_svm.fit(x_train, y_train)

SVC(gamma='auto')

In [18]:
model_svm.score(x_test, y_test)

1.0

## Grid Search Cross Validation

In [19]:
from sklearn.model_selection import GridSearchCV

In [21]:
classifier= GridSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel':['rbf','linear'],
},cv=5, return_train_score=False)

# check the model acc for possible combination of c and kernel (4*2=8)
# no need for train_test_split
# data is divided into 5 parts for cross  validation , cv=5

In [22]:
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [23]:
classifier.cv_results_

{'mean_fit_time': array([0.0061173 , 0.00263858, 0.0031661 , 0.00425892, 0.00511427,
        0.00519414, 0.00464764, 0.0037097 ]),
 'std_fit_time': array([3.42447901e-03, 6.39321098e-05, 5.59486219e-04, 2.70721390e-04,
        4.99665970e-04, 9.72230418e-04, 4.01232773e-04, 1.06076084e-03]),
 'mean_score_time': array([0.00308666, 0.00207806, 0.00257444, 0.00295796, 0.00406046,
        0.00397468, 0.0037674 , 0.00259814]),
 'std_score_time': array([1.32758044e-03, 5.95447239e-05, 7.42978903e-04, 5.33664286e-04,
        3.65841525e-04, 6.59765460e-04, 4.49899652e-04, 5.74288084e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [26]:
result= pd.DataFrame(classifier.cv_results_)
result[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

## Randomized Search CV (cross validation )

In [27]:
from sklearn.model_selection import RandomizedSearchCV

In [28]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C' : [1,10,20,30,40, 50, 60, 70],
    'kernel' :['rbf','linear'],
},n_iter = 5,cv = 5,return_train_score = False)

# when iteration/combinations  are maximum it is used
# n_iter = 5  randomly select 4 combinations which gives max acc
# 8*2 = 16 so random 5 are selected

In [29]:
classifier_r.fit(x,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=5,
                   param_distributions={'C': [1, 10, 20, 30, 40, 50, 60, 70],
                                        'kernel': ['rbf', 'linear']})

In [30]:
results = pd.DataFrame(classifier_r.cv_results_)
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       20       linear         0.966667
1       60       linear         0.966667
2       10       linear         0.973333
3       40       linear         0.960000
4       20          rbf         0.966667